package jichttp

const (
	_method_get   = "GET"
	_method_post  = "POST"
	_token        = "eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJuYmYiOjE2NjkxNzExNzksImV4cCI6MTY2OTE3NDc3OSwiaXNzIjoiaHR0cHM6Ly9pZHMuY2hpbmEtaW52LmNuIiwiYXVkIjpbImVjb3N5cyIsImVjb3N5c3JjIiwic2VuZGNvZGUiLCJzdmMiXSwiY2xpZW50X2lkIjoiZWNvc3lzIiwic3ViIjoibGliaW5Ac2RqaWN0ZWMuY29tIiwiYXV0aF90aW1lIjoxNjY5MTY3MjQ5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiLmnY7lvawiLCJlbWFpbCI6ImxpYmluQHNkamljdGVjLmNvbSIsImRlcGFydG1lbnQiOiLkuLTml7bpg6jpl6giLCJjb21wYW55Ijoi5bu65oqV5pWw5o2u56eR5oqA77yI5bGx5Lic77yJ5pyJ6ZmQ5YWs5Y-4IiwiZGl2aXNpb24iOiIiLCJlbXBsb3llZWlkIjoiMTIzODk1IiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwianRpIjoiQ0M1MjIxM0QyOTM2NUFERUM1RkVGREQ4NzJGOTU3NEYiLCJpYXQiOjE2NjkxNjcyNDksInNjb3BlIjpbImVjb3N5cyIsImVjb3N5c3JjIiwib3BlbmlkIiwic2VuZGNvZGUiLCJzdmMiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsiU21zQ29kZSJdfQ.ffVrSv1fAqfMwZZekkMPBLqAQc5Xt-NHXMLOPXBNQbix9V2zzlxleQyZXPltuGnJYxs54PvPMAq1_KZw0-dAY8Dm3wuuI4BxSKWq-1gxRIjvbOJYRYlEwAjwEIMjgLiyk6O-B0ijVdQ1NhqQn-jvO-3jWuUXQ_9EOQzfSrhOmHpF5ERAM2EM1EGQbmA-rqgjAHV71OfQDwad-q5igX6NxrA_YLZpU-Y2xSKCqeq0yWtc4Ut-uynX0vR_UmAcjs71YGU3fK3_ExXtE-bVCdSW_XOY_Apk6q7y1pKi7GjF-W3ao_t3d2i0dY8FuQPfXjJeYxM9UOJt1-WolMgvemuygw"
	_token_url    = "https://ecosys-web.china-inv.cn/api/score/scoreTotal"
	_news_url     = "https://ecosys-web.china-inv.cn/api/content/list"
	_userInfo_url = "https://ecosys-web.china-inv.cn/api/user/getUserInfo"
	_view_url     = "https://ecosys-web.china-inv.cn/api/content"
	_behavior_url = "https://ecosys-web.china-inv.cn/api/content/independent/content/behavior"
)
